#!/usr/bin/env python3
"""Publish curated numeric summaries and standalone figures, never private notes."""
import hashlib
import csv
import json
from pathlib import Path
import subprocess
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from log_experiment import append_entry

ROOT=Path(__file__).resolve().parents[1]
LABELS={'strict_fcfs':'Strict-FCFS (HOL baseline)','frfcfs':'FR-FCFS','frfcfs_aging':'FR-FCFS + aging'}
COLORS={'strict_fcfs':'#697386','frfcfs':'#2b6cb0','frfcfs_aging':'#d97706'}

def write_traces(base):
    def events(policy, workload):
        with (ROOT/base[policy,workload]['path']/'events.csv').open() as f:
            return [(r[0],list(map(int,r[1:]))) for r in csv.reader(f)]
    def table(commands, target=None):
        lines=['| Cycle | Request sequence | Command | Bank | Row | Note |',
               '|---:|---:|---|---:|---:|---|']
        for c in commands:
            note='Protected request' if target is not None and c[1]==target else ''
            lines.append(f'| {c[0]} | {c[1]} | {["ACT","READ","WRITE","PRE"][c[2]]} | {c[3]} | {c[4]} | {note} |')
        return '\n'.join(lines)
    conflict=[v for k,v in events('strict_fcfs','row_conflict') if k=='C']
    first=next(c for c in conflict if c[1]>=210 and c[2]==3)
    sequence=[c for c in conflict if c[1]==first[1]]
    parallel=[v for k,v in events('frfcfs','random') if k=='C']
    index=next(i for i,c in enumerate(parallel[:-1]) if c[1]>=210 and c[2]==0 and
               parallel[i+1][2]==0 and parallel[i+1][3]!=c[3] and parallel[i+1][0]-c[0]<3)
    start=parallel[index][0]
    overlap=[c for c in parallel if start<=c[0]<=start+7]
    aging=events('frfcfs_aging','hot_cold')
    protected=next(v for k,v in aging if k=='P' and v[1]>=210)
    completed=next(v for k,v in aging if k=='E' and v[1]==protected[1])
    protected_commands=[v for k,v in aging if k=='C' and protected[0]-3<=v[0]<=completed[0]+2]
    text=f'''# Annotated command traces

Extracted from the seed-42 performance runs generated by `make perf`. Cycles are
command-sampling edges. Request sequence numbers include the ten directed requests
and 200 warm-up requests. Timing profile is tRCD/tRP/tRAS/tCCD/tWR = 3/3/6/2/3.

## Row conflict: Strict-FCFS (HOL baseline)

{table(sequence)}

The same request must PRE, wait tRP, ACT, wait tRCD, then issue its column command.
Strict-FCFS issues no younger request's command during those waits. PRE also waits
for the old row's tRAS and most recent write's tWR; the monitor checks both.

## Overlapping bank preparation: FR-FCFS

{table(overlap)}

The first two ACTs target different banks less than tRCD cycles apart. The second
bank starts activation while the first is waiting; the shared command bus still
issues at most one command per edge. Column commands additionally obey global tCCD.

## Aging intervention: FR-FCFS with aging

Protection starts at cycle {protected[0]} for request {protected[1]}, whose column
command issues at cycle {completed[0]} ({completed[2]} cycles after protection).

{table(protected_commands,protected[1])}

During the protected wait, unrelated column commands cannot consume tCCD opportunities.
The protected conflict changes the open row and completes its own PRE/ACT/column
sequence. Row-hit preference resumes after its column command; response ordering
and response backpressure remain independently enforced.
'''
    (ROOT/'docs/traces.md').write_text(text)

def main():
    result_dir=ROOT/'results'; result_dir.mkdir(exist_ok=True)
    regression=json.loads((ROOT/'build/regress_summary.json').read_text())
    tests=json.loads((ROOT/'build/test_summary.json').read_text())
    perf=json.loads((ROOT/'build/perf_summary.json').read_text())
    formal=json.loads((ROOT/'build/formal/summary.json').read_text())
    metrics=perf['results']
    coverage_keys=['protection','same_addr_block','independent_bypass','overlap','full','bank_overlap','protected_owner_block']
    coverage={k:sum(x.get(k,0) for x in regression['results']+tests['results']) for k in coverage_keys}
    public={'verilator':regression['verilator'],
        'yosys':subprocess.run(['yosys','-V'],capture_output=True,text=True,check=True).stdout.strip(),
        'regression_runs':len(regression['results']),
        'accepted_transactions':sum(x['accepted'] for x in regression['results']),
        'directed_and_corner_runs':len(tests['results']),
        'coverage_counts':coverage,'formal':formal,
        'performance':[{k:v for k,v in r.items() if k!='path'} for r in metrics],
        'asic_status':('Frozen 30-point UCSB DC sweep completed; 25 setup targets pass; hold/max-capacitance violations remain; see docs/asic-results.md'
                       if (ROOT/'results/dc_sweep/summary.json').exists() else
                       'Initial UCSB 5 ns DC baseline completed; setup met, hold/max-capacitance violations remain; see docs/ucsb-baseline.md'
                       if (ROOT/'results/dc_baseline/summary.json').exists() else
                       'Pending UCSB lab access and technology library configuration'),
        'rtl_sha256':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted((ROOT/'rtl').glob('*.sv'))}}
    (result_dir/'local_summary.json').write_text(json.dumps(public,indent=2)+'\n')
    selected=['row_hit','row_conflict','random','hot_cold','hol']
    base={(r['policy_name'],r['workload']):r for r in metrics
          if r.get('ready_percent',100)==100 and r.get('offered_interval',1)==1}
    fig,axes=plt.subplots(1,3,figsize=(15,4.6),layout='constrained')
    x=np.arange(len(selected)); width=.25
    for i,p in enumerate(LABELS):
        axes[0].bar(x+(i-1)*width,[base[p,w]['metrics']['responses_per_cycle'] for w in selected],
                    width,label=LABELS[p],color=COLORS[p])
    axes[0].set_xticks(x,[w.replace('_','\n') for w in selected]); axes[0].set_ylabel('Responses / cycle')
    axes[0].set_title('Throughput: fixed request sequences'); axes[0].set_ylim(0,.55)
    for i,p in enumerate(LABELS):
        m=base[p,'hot_cold']['metrics']['latency']['end_to_end']
        axes[1].bar(np.arange(3)+(i-1)*width,[m['mean'],m['p99'],m['max']],width,color=COLORS[p])
    axes[1].set_xticks(np.arange(3),['Mean','p99','Maximum']); axes[1].set_ylabel('Cycles from acceptance to response')
    axes[1].set_title('Hot/cold latency: locality versus aging')
    for p in LABELS:
        points=sorted([r for r in metrics if r['policy_name']==p and r['workload']=='random' and r['ready_percent']==100],
                      key=lambda r:1/r['offered_interval'])
        axes[2].plot([1/r['offered_interval'] for r in points],
                     [r['metrics']['latency']['end_to_end']['mean'] for r in points],
                     marker='o',color=COLORS[p],label=LABELS[p])
    axes[2].set_xlabel('Offered requests / cycle'); axes[2].set_ylabel('Mean response latency (cycles)')
    axes[2].set_title('Random traffic: offered-load sweep')
    for ax in axes:
        ax.spines[['top','right']].set_visible(False); ax.grid(axis='y',alpha=.2); ax.set_axisbelow(True)
    handles,labels=axes[0].get_legend_handles_labels()
    fig.legend(handles,labels,loc='outside lower center',ncols=3,fontsize=9)
    fig.savefig(result_dir/'performance.png',dpi=180)
    fig.savefig(result_dir/'performance.pdf')
    plt.close(fig)
    write_traces(base)
    rows=[]
    for w in selected:
        for p in LABELS:
            m=base[p,w]['metrics']; lat=m['latency']['end_to_end']
            rows.append(f'| {w} | {LABELS[p]} | {m["responses_per_cycle"]:.3f} | {lat["mean"]:.1f} | {lat["p99"]} | {lat["max"]} |')
    formal_rows='\n'.join(f'| {x["task"]} | {x["mode"]} | {x["depth"] if x["depth"] else "unbounded"} | {x["status"]} |' for x in formal)
    text=f'''# Measured local results

These verification and performance results come from executed local runs.
ASIC status: {public['asic_status']}.
See the [UCSB flow](lab-flow.md) and [completed ASIC sweep](asic-results.md).
PrimeTime was not run; mapped results are pre-layout.

## Verification

- Verilator: `{public['verilator']}`.
- Yosys: `{public['yosys']}`.
- {public['regression_runs']} regression runs passed; {public['accepted_transactions']:,} accepted transactions,
  comprising 100 seeds × 10,000 workload requests × three policies plus directed preludes.
- {public['directed_and_corner_runs']} directed/workload/reset/parameter-corner runs passed.
- Two legal model boundary traces, eight expected-failure traces, and the defensive
  existing-owner aging arbitration test passed.
- The response-refill test passed: eight consecutive independent handshakes,
  stable stalled payloads, ordered same-address consumption, and reset cancellation.
- RTL lint passed. Optional generic Yosys synthesis completed; it is a synthesizability check.
- Private-directory ignore/tracking and allowlisted lab-bundle checks passed.

Aggregated coverage counts (events/cycles, not percentages):

```json
{json.dumps(coverage,indent=2)}
```

Same-address blocking counts blocked transaction-cycles. The zero existing-owner
count reflects the normal bank-preparation invariant; its defensive branch is
tested separately by `tb_scheduler`, as described in the verification plan.

## Formal evidence and limits

| Task | Mode | Depth | Outcome |
|---|---|---|---|
{formal_rows}

Integrated BMC covers symbolic data, addresses, operation mix, tags, and backpressure
for a two-slot configuration. It is not an unbounded data-correctness proof.
The bank proof establishes timing-permission equivalence to independent elapsed-cycle
counters under legal issue assumptions. The progress proof checks mixed reads/writes,
all four banks, two slots, fixed one-cycle reads, small positive timing values and
age threshold three. Payloads are zero; response readiness is unrestricted. It proves
the conservative 63-cycle pending-service bound for this reduced control configuration,
plus ownership/ordering/capacity assertions. It does not prove all parameter settings.

Earlier integrated 80-cycle attempts with Z3 and ABC timed out. Splitting focused
control proofs from bounded symbolic-data checks made the final suite tractable.

## Performance

Simulation configuration: four banks, eight rows × eight columns per bank, 32-bit
words, 16 outstanding slots, read latency three; timing 3/3/6/2/3 and aging 128.
Each experiment uses seed 42, 200 warm-up requests, 2,000 measured requests, fixed
request sequences, and complete drain. The table uses always-ready responses and
one offered request per cycle. Throughput includes the measured cohort's drain.

| Workload | Policy | Responses/cycle | Mean latency | p99 | Maximum |
|---|---|---:|---:|---:|---:|
{chr(10).join(rows)}

![Reproducible throughput, tail-latency and offered-load comparisons](../results/performance.png)

[Annotated command traces](traces.md) show a row conflict, overlapping bank
activations, and a measured aging intervention from these runs.

The response holding register now consumes and refills on the same edge for
already-eligible independent transactions. The default tCCD=2 limits sustained
column-command throughput to 0.5/cycle; row-hit traffic approaches that limit across
all policies. A separate tCCD=1 capacity experiment isolates the response path's
one-per-cycle capability; see [before/after response-refill results](response-refill.md).
FR-FCFS
improves locality and bank overlap on conflicts and random traffic. Hot/cold traffic
shows its tail-latency cost; aging trades some throughput for a shorter tail.
At low offered load, latency reflects individual service rather than a full queue.
These are abstract word-transfer results, not physical DDR bandwidth measurements.

## Reproduce

The [20-seed stability study](performance-stability.md) records the subsequent
540 final-design runs and 60 historical paired runs, including the random/50%
p99 tradeoff and deterministic hot/cold and HOL stimulus limitations.
See the [portfolio release audit](release-audit.md) for clean-checkout validation.

```sh
make lint test
make regress SEEDS=100 N=10000 JOBS=4
make formal
make perf
make synth-local-sanity
make lab-bundle
make report
```

Machine-readable public results and RTL hashes are in `results/local_summary.json`.
Detailed commands, source hashes, logs and CSV events are retained locally under
`build/`. The publication script reads only explicitly selected build summaries
and traces; it never reads the private engineering notebook.
'''
    (ROOT/'docs/results.md').write_text(text)
    append_entry('整理公開驗證與效能報告','以實際輸出建立可重現的作品集證據。',
                 '產生數值摘要、PNG／PDF 圖表及結果文件。','results/*、docs/results.md',
                 'python3 scripts/report.py','完成；ASIC 狀態依已存在的基準報告分別標示。','無',
                 '僅讀取白名單實驗產物；不讀取或發布私人筆記。','參閱獨立 UCSB 基準報告與尚未完成的時序檢查。')

if __name__=='__main__': main()
